package com.revature.soap_server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.3
 * 2017-01-10T14:18:22.739-05:00
 * Generated source version: 3.1.3
 * 
 */
@WebService(targetNamespace = "http://soap_server.revature.com/", name = "HelloWorld")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorld {

    @WebMethod
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.SayHiResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "work", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.Work")
    @ResponseWrapper(localName = "workResponse", targetNamespace = "http://soap_server.revature.com/", className = "com.revature.soap_server.WorkResponse")
    public void work();
}
